import tabNav from "./modules/tabnav.js";
tabNav();
import accordion from "./modules/accordion.js";
accordion();
import smoothScroll from "./modules/smoothScroll.js";
smoothScroll();
import scrollAnim from "./modules/scrollAnim.js";
scrollAnim();
import menuMobile from "./modules/menuMobile.js";
menuMobile();
